# Generated by Django 5.1.5 on 2025-02-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('open_24hrs', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_glucose_test', models.DateTimeField()),
                ('index', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='InsulineSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopbuzzer', models.DateTimeField()),
                ('confirm_type', models.DateTimeField()),
                ('mount_syringe', models.DateTimeField()),
                ('start_dose', models.DateTimeField()),
                ('confirm_dose', models.DateTimeField()),
                ('confirm_insulin_admin', models.DateTimeField()),
                ('insulin_dose', models.IntegerField()),
                ('insulin_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('emergency_email', models.CharField(max_length=200)),
                ('emergency_mobile', models.PositiveIntegerField()),
                ('medical_care', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('last_hba1c', models.PositiveIntegerField()),
                ('stroke_suffered', models.BooleanField(default=False)),
                ('blood_preassure', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('dv', models.CharField(max_length=1)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('first_surname', models.CharField(max_length=100)),
                ('second_surname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
                ('id_device', models.CharField(max_length=15)),
                ('geolocation', models.CharField(max_length=100)),
                ('send_data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_date', models.DateTimeField()),
                ('type', models.CharField(default='NPH', max_length=50)),
                ('quantity', models.IntegerField()),
                ('first_administration', models.TimeField()),
                ('second_administration', models.TimeField()),
            ],
        ),
    ]
