# Generated by Django 5.1.5 on 2025-02-24 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsulinSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_buzzer', models.DateTimeField()),
                ('confirm_type', models.DateTimeField()),
                ('mount_syringe', models.DateTimeField()),
                ('start_dose', models.DateTimeField()),
                ('confirm_dose', models.DateTimeField()),
                ('confirm_insulin_admin', models.DateTimeField()),
                ('insulin_dose', models.IntegerField()),
                ('insulin_type', models.CharField(max_length=50)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sart.sample')),
            ],
        ),
        migrations.DeleteModel(
            name='InsulineSample',
        ),
        migrations.AddField(
            model_name='glucosesample',
            name='sample',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='sart.sample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='sart.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='sart.person'),
            preserve_default=False,
        ),
    ]
