# Generated by Django 5.1.5 on 2025-04-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sart', '0002_insulinsample_delete_insulinesample_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Patient',
        ),
        migrations.AddField(
            model_name='personnel',
            name='centers',
            field=models.ManyToManyField(related_name='centers', to='sart.center'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='patients',
            field=models.ManyToManyField(related_name='personnels', to='sart.patient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='sart.patient'),
            preserve_default=False,
        ),
    ]
