# Generated by Django 5.1.5 on 2025-04-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sart', '0003_rename_paciente_patient_personnel_centers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='personnels',
            field=models.ManyToManyField(related_name='patients', to='sart.personnel'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
