# Generated by Django 5.1.5 on 2025-04-28 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sart', '0004_remove_patient_email_remove_personnel_patients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id_device', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='id_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='sart.device'),
        ),
    ]
