# Generated by Django 5.1.5 on 2025-04-29 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sart', '0005_device_alter_sample_id_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sart.patient'),
        ),
    ]
