# Generated by Django 5.1.5 on 2025-09-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sart', '0007_personnel_groups_personnel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adherence',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='glucose',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='insulin_type',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nph',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
