# Generated by Django 5.1.5 on 2025-09-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sart', '0008_patient_adherence_patient_glucose_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id_device',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='id_device',
            new_name='device',
        ),
    ]
