volumes:
  mysql-data:

services:

  database:
    image: mysql
    restart: always
    container_name: database
    environment:  
      MYSQL_ROOT_PASSWORD: sart
      MYSQL_DATABASE: sart
      MYSQL_PORT: 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    expose:
      - 3306
    volumes:
      - ./data:/var/lib/mysql
    attach: false

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SECRET_KEY=django-insecure-@vb7#n+=9bgqq!io+8n=vlex6(1n%em!ygi7^12!+=h3-^o&_9
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=sart
      - DB_USER=sart
      - DB_PASSWORD=sart
      - DB_HOST=${DATABASE_HOST}
    expose:
      - 8000
